/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Gravity Jack (https://sketchfab.com/gravityjack)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/earth-e7499c9024444299afb9a01107f97523
title: Earth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'


export default function Earth(props) {
  const { nodes, materials } = useGLTF('/earth.glb')

  const ref = useRef()

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    ref.current.rotation.x = THREE.MathUtils.lerp(ref.current.rotation.x, Math.cos(t) / 4 + 0.25, 0.1)
    ref.current.rotation.y = THREE.MathUtils.lerp(ref.current.rotation.y, Math.sin(t) / 4 - 10, 0.1)
    ref.current.rotation.z = THREE.MathUtils.lerp(ref.current.rotation.z, 2 + Math.sin(t) / 4, 0.1)
    ref.current.position.y = THREE.MathUtils.lerp(ref.current.position.y, Math.sin(t / 2) / 2, 0.1)
  })

  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.85, 0, -0.35]} rotation={[-Math.PI / 2, 0, 0.4]}>
            <mesh geometry={nodes.earth_earth_0.geometry} material={materials.earth} />
          </group>
          <group position={[0.85, 0, -0.35]} rotation={[-Math.PI / 2, 0, 0.4]}>
            <mesh geometry={nodes.shippingRoutes_shippingRoutes_0.geometry} material={materials.shippingRoutes} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/earth.glb')
